"""harness: モデル比較ハーネス (L3)。

``llmkit`` (L2) が再エクスポートする公開シンボルだけを使う。``llmkit`` の
サブモジュール (``llmkit.client`` 等) を直接 import しないことで、層の境界を
散文の主張ではなく機械検証できる状態に保つ。逆向き (``llmkit`` からの
``harness`` 参照) も存在しない。

``__all__`` は各サブモジュールが宣言する ``__all__`` の和集合であり、
``llmkit/__init__.py`` と同じ方針で維持する。
"""

from harness.gpu import (
    DEFAULT_NVIDIA_SMI_COMMAND,
    DEFAULT_TIMEOUT_S,
    CommandResult,
    CommandRunner,
    GpuMemory,
    NvidiaSmiProbe,
    VramProbe,
    run_command,
)
from harness.records import (
    MIXED_SPEED_SOURCE,
    RECORD_KEYS,
    RECORD_SCHEMA_VERSION,
    MetricSummary,
    ModelSummary,
    RecordError,
    ResponseFacts,
    RunPhase,
    RunRecord,
    RunSummary,
    SpeedMetrics,
    SpeedSource,
    VramReading,
    summarize_records,
    wallclock_tokens_per_second,
)
from harness.report import (
    COMPARISON_TABLE_HEADER,
    DIRECTORY_TIMESTAMP_FORMAT,
    MISSING_CELL,
    RECORDS_FILENAME,
    REPORT_FILENAME,
    RESPONSE_PREVIEW_CHARS,
    RUN_JSON_FILENAME,
    ReportPaths,
    build_run_json,
    render_records_jsonl,
    render_report,
    run_output_dir,
    write_run_outputs,
)
from harness.runner import (
    MANIFESTS_DIRNAME,
    CasePlan,
    Clock,
    RunPlan,
    RunResult,
    SuiteFilters,
    fingerprint_digest,
    fingerprint_inputs,
    plan_run,
    run_fingerprint,
    run_suite,
)
from harness.suite import (
    ComparisonSuite,
    ModelCase,
    PromptSpec,
    SuiteMeta,
    apply_case,
    load_suite,
    suite_sha256,
)

__all__ = [
    "COMPARISON_TABLE_HEADER",
    "DEFAULT_NVIDIA_SMI_COMMAND",
    "DEFAULT_TIMEOUT_S",
    "DIRECTORY_TIMESTAMP_FORMAT",
    "MANIFESTS_DIRNAME",
    "MISSING_CELL",
    "MIXED_SPEED_SOURCE",
    "RECORDS_FILENAME",
    "RECORD_KEYS",
    "RECORD_SCHEMA_VERSION",
    "REPORT_FILENAME",
    "RESPONSE_PREVIEW_CHARS",
    "RUN_JSON_FILENAME",
    "CasePlan",
    "Clock",
    "CommandResult",
    "CommandRunner",
    "ComparisonSuite",
    "GpuMemory",
    "MetricSummary",
    "ModelCase",
    "ModelSummary",
    "NvidiaSmiProbe",
    "PromptSpec",
    "RecordError",
    "ReportPaths",
    "ResponseFacts",
    "RunPhase",
    "RunPlan",
    "RunRecord",
    "RunResult",
    "RunSummary",
    "SpeedMetrics",
    "SpeedSource",
    "SuiteFilters",
    "SuiteMeta",
    "VramProbe",
    "VramReading",
    "apply_case",
    "build_run_json",
    "fingerprint_digest",
    "fingerprint_inputs",
    "load_suite",
    "plan_run",
    "render_records_jsonl",
    "render_report",
    "run_command",
    "run_fingerprint",
    "run_output_dir",
    "run_suite",
    "suite_sha256",
    "summarize_records",
    "wallclock_tokens_per_second",
    "write_run_outputs",
]
